/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

import { MediaAssetDTOSchema } from "./media-asset-dto.gen";
import { PublishingWindowDTOSchema } from "./publishing-window-dto.gen";
import { AnalyticsBucketDTOSchema } from "./analytics-bucket-dto.gen";

export const AdvancedCasesDTOSchema = v.object({
  title: v.string([v.minLength(3), v.maxLength(80)]),
  subtitle: v.optional(v.string()),
  isFeatured: v.transform(v.unknown(), v => v === "on" || v === "true" || v === true, v.boolean()),
  publishWindow: PublishingWindowDTOSchema,
  media: MediaAssetDTOSchema,
  analytics: AnalyticsBucketDTOSchema,
  tags: v.array(v.any()),
  coordinates: v.tuple([v.transform(v.string(), (input) => input === "" ? Number.NaN : Number(input), v.number()), v.transform(v.string(), (input) => input === "" ? Number.NaN : Number(input), v.number())]),
  state: v.picklist(["draft", "scheduled", "published"]),
});
