/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

export const AnalyticsBucketDTOSchema = v.object({
  scoresByChannel: v.record(v.picklist(["seo", "email", "ads"]), v.transform(v.string(), (input) => input === "" ? Number.NaN : Number(input), v.number())),
  reviewers: v.set(v.string()),
  weights: v.map(v.string(), v.transform(v.string(), (input) => input === "" ? Number.NaN : Number(input), v.number())),
});
