/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

export const MediaAssetDTOSchema = v.object({
  name: v.string(),
  file: v.instance(File),
  preview: BlobSchema,
});
