/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

export const PublishingWindowDTOSchema = v.object({
  startsAt: v.transform(v.string(), v => new Date(v), v.date()),
  endsAt: v.transform(v.string(), v => new Date(v), v.date()),
});
