/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

export const AddressDTOSchema = v.object({
  street: v.string([v.minLength(5, "กรุณากรอกรายละเอียดที่อยู่")]),
  city: v.string(),
});
