/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

export const ExperienceDTOSchema = v.object({
  company: v.string(),
  years: v.transform(v.string(), (input) => input === "" ? Number.NaN : Number(input), v.number([v.minValue(1, "ต้องทำงานมาอย่างน้อย 1 ปี")])),
});
