/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
export { AddressDTOSchema } from "./address-dto.schema";
export { ExperienceDTOSchema } from "./experience-dto.schema";
export { JobApplicationDTOSchema } from "./job-application-dto.schema";
