/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

import { AddressDTOSchema } from "./address-dto.schema";
import { ExperienceDTOSchema } from "./experience-dto.schema";

export const JobApplicationDTOSchema = v.object({
  email: v.string([v.email("อีเมลไม่ถูกต้อง")]),
  address: AddressDTOSchema,
  experiences: v.array(ExperienceDTOSchema),
});
