#!/usr/bin/env node
import { Command } from "commander";
import { glob } from "glob";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

import { SAVCompiler } from "./index.js";

const GENERATED_FILE_HEADER =
  "/**\n * GENERATED BY SAV COMPILER\n * DO NOT EDIT MANUALLY\n */\n";

function hasFileExtension(targetPath: string): boolean {
  return path.extname(path.basename(targetPath)) !== "";
}

function normalizeGeneratedFileSuffix(suffix: string): string {
  const trimmed = suffix.trim();
  const withoutTs = trimmed.replace(/\.ts$/i, "");
  return withoutTs || ".gen";
}

const program = new Command();

program
  .name("valiact")
  .description("Generate Valibot schemas from TypeScript DTOs")
  .version("0.2.0");

program
  .command("generate")
  .description("Scan files and generate separate schema files")
  .option(
    "-i, --input <pattern>",
    "Glob pattern for input files",
    "**/actions/**/*.ts",
  )
  .option(
    "-o, --output <file> or <directory>",
    "Optional single output file path for aggregated schemas",
  )
  .option(
    "-s, --suffix <suffix>",
    "Optional suffix for generated schema folders when a source has multiple DTOs",
    "-schema",
  )
  .option(
    "-sf, --suffix-file <suffix>",
    "Optional suffix for generated .ts schema files (e.g. .gen, -schema, .schema.ts)",
    ".gen",
  )
  .action(async (options) => {
    console.log("SAV: Starting compiler...");

    const compiler = new SAVCompiler();
    const folderSuffix = String(options.suffix ?? "-schema").trim() || "-schema";
    const generatedFileSuffix = normalizeGeneratedFileSuffix(
      String(options.suffixFile ?? ".gen"),
    );
    const files = await glob(options.input, {
      absolute: true,
      ignore: [`**/*${generatedFileSuffix}.ts`, "**/dist/**", "**/node_modules/**"],
    });

    if (files.length === 0) {
      console.warn(`SAV: No files found matching pattern: ${options.input}`);
      return;
    }

    const sortedFiles = [...files].sort();

    const emitSchemaModules = (file: string, outputDir: string): number => {
      const schemaModules = compiler.processFileAsModules(file, generatedFileSuffix);

      if (schemaModules.length === 0) {
        return 0;
      }

      const fileObject = path.parse(file);
      const legacyOutPath = path.join(
        outputDir,
        `${fileObject.name}${generatedFileSuffix}.ts`,
      );
      const schemasDirPath = path.join(
        outputDir,
        `${fileObject.name}${folderSuffix}`,
      );

      if (schemaModules.length === 1) {
        rmSync(schemasDirPath, { recursive: true, force: true });

        const finalOutput = `${GENERATED_FILE_HEADER}${schemaModules[0]?.content ?? ""}`;
        writeFileSync(legacyOutPath, finalOutput);
        console.log(
          `SAV: Generated ${path.relative(process.cwd(), legacyOutPath)}`,
        );
        return 1;
      }

      rmSync(schemasDirPath, { recursive: true, force: true });
      mkdirSync(schemasDirPath, { recursive: true });

      for (const module of schemaModules) {
        const moduleOutPath = path.join(schemasDirPath, module.fileName);
        writeFileSync(moduleOutPath, `${GENERATED_FILE_HEADER}${module.content}`);
      }

      const indexContent = `${GENERATED_FILE_HEADER}${schemaModules
        .map(
          (module) =>
            `export { ${module.schemaName} } from "./${module.fileName.replace(/\.ts$/, "")}";`,
        )
        .join("\n")}\n`;
      writeFileSync(path.join(schemasDirPath, "index.ts"), indexContent);

      const legacyOutput = `${GENERATED_FILE_HEADER}export * from "./${fileObject.name}${folderSuffix}";\n`;
      writeFileSync(legacyOutPath, legacyOutput);

      console.log(`SAV: Generated ${path.relative(process.cwd(), schemasDirPath)}`);
      console.log(`SAV: Updated ${path.relative(process.cwd(), legacyOutPath)}`);
      return schemaModules.length;
    };

    if (options.output) {
      const resolvedOutputPath = path.resolve(options.output);

      if (hasFileExtension(resolvedOutputPath)) {
        const schemaCode = compiler.processFiles(sortedFiles);
        mkdirSync(path.dirname(resolvedOutputPath), { recursive: true });
        const finalOutput = `${GENERATED_FILE_HEADER}${schemaCode}`;
        writeFileSync(resolvedOutputPath, finalOutput);
        console.log(
          `SAV: Generated ${path.relative(process.cwd(), resolvedOutputPath)}`,
        );
        return;
      }

      mkdirSync(resolvedOutputPath, { recursive: true });

      let generatedCount = 0;

      for (const file of sortedFiles) {
        mkdirSync(resolvedOutputPath, { recursive: true });
        generatedCount += emitSchemaModules(file, resolvedOutputPath);
      }

      console.log(
        `SAV: Successfully generated ${generatedCount} schema modules.`,
      );
      return;
    }

    let generatedCount = 0;

    for (const file of sortedFiles) {
      generatedCount += emitSchemaModules(file, path.parse(file).dir);
    }

    console.log(
      `SAV: Successfully generated ${generatedCount} schema modules.`,
    );
  });

program.parse();
