#!/usr/bin/env node
import { Command } from "commander";
import { glob } from "glob";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

import { SAVCompiler } from "./index.js";

const program = new Command();

program
  .name("valiact")
  .description("Generate Valibot schemas from TypeScript DTOs")
  .version("0.2.0");

program
  .command("generate")
  .description("Scan files and generate separate schema files")
  .option(
    "-i, --input <pattern>",
    "Glob pattern for input files",
    "**/actions/**/*.ts",
  )
  .option(
    "-o, --output <file>",
    "Optional single output file path for aggregated schemas",
  )
  .option(
    "-s, --suffix <suffix>",
    "Optional suffix for generated schema files",
    "-schema",
  )
  .option(
    "-sf, --suffix-file <suffix>",
    "Optional suffix for generated schema files when using single file output",
    ".gen",
  )
  .action(async (options) => {
    console.log("SAV: Starting compiler...");

    const compiler = new SAVCompiler();
    const files = await glob(options.input, {
      absolute: true,
      ignore: ["**/*.gen.ts", "**/dist/**", "**/node_modules/**"],
    });

    if (files.length === 0) {
      console.warn(`SAV: No files found matching pattern: ${options.input}`);
      return;
    }

    const sortedFiles = [...files].sort();

    if (options.output) {
      const schemaCode = compiler.processFiles(sortedFiles);
      const outPath = path.resolve(options.output);
      mkdirSync(path.dirname(outPath), { recursive: true });
      const finalOutput = `/**\n * GENERATED BY SAV COMPILER\n * DO NOT EDIT MANUALLY\n */\n${schemaCode}`;
      writeFileSync(outPath, finalOutput);
      console.log(`SAV: Generated ${path.relative(process.cwd(), outPath)}`);
      return;
    }

    let generatedCount = 0;

    for (const file of sortedFiles) {
      const schemaModules = compiler.processFileAsModules(file);

      if (schemaModules.length === 0) {
        continue;
      }

      const fileObject = path.parse(file);
      const header =
        "/**\n * GENERATED BY SAV COMPILER\n * DO NOT EDIT MANUALLY\n */\n";
      const legacyOutPath = path.join(
        fileObject.dir,
        `${fileObject.name}${options.suffixFile}.ts`,
      );
      const schemasDirPath = path.join(
        fileObject.dir,
        `${fileObject.name}${options.suffix}`,
      );

      if (schemaModules.length === 1) {
        rmSync(schemasDirPath, { recursive: true, force: true });

        const finalOutput = `${header}${schemaModules[0]?.content ?? ""}`;
        writeFileSync(legacyOutPath, finalOutput);
        console.log(
          `SAV: Generated ${path.relative(process.cwd(), legacyOutPath)}`,
        );
        generatedCount += 1;
        continue;
      }

      rmSync(schemasDirPath, { recursive: true, force: true });
      mkdirSync(schemasDirPath, { recursive: true });

      for (const module of schemaModules) {
        const moduleOutPath = path.join(schemasDirPath, module.fileName);
        writeFileSync(moduleOutPath, `${header}${module.content}`);
      }

      const indexContent = `${header}${schemaModules
        .map(
          (module) =>
            `export { ${module.schemaName} } from "./${module.fileName.replace(/\.ts$/, "")}";`,
        )
        .join("\n")}\n`;
      writeFileSync(path.join(schemasDirPath, "index.ts"), indexContent);

      console.log(
        `SAV: Generated ${path.relative(process.cwd(), schemasDirPath)}`,
      );
      console.log(
        `SAV: Updated ${path.relative(process.cwd(), legacyOutPath)}`,
      );
      generatedCount += schemaModules.length;
    }

    console.log(
      `SAV: Successfully generated ${generatedCount} schema modules.`,
    );
  });

program.parse();
