#!/usr/bin/env node
import { Command } from "commander";
import { glob } from "glob";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

import { SAVCompiler } from "./index.js";

const program = new Command();

program
  .name("sav-validator")
  .description("Generate Valibot schemas from TypeScript DTOs")
  .version("0.2.0");

program
  .command("generate")
  .description("Scan files and generate separate schema files")
  .option(
    "-i, --input <pattern>",
    "Glob pattern for input files",
    "**/actions/**/*.ts",
  )
  .option(
    "-o, --output <file>",
    "Optional single output file path for aggregated schemas",
  )
  .action(async (options) => {
    console.log("SAV: Starting compiler...");

    const compiler = new SAVCompiler();
    const files = await glob(options.input, {
      absolute: true,
      ignore: ["**/*.gen.ts", "**/dist/**", "**/node_modules/**"],
    });

    if (files.length === 0) {
      console.warn(`SAV: No files found matching pattern: ${options.input}`);
      return;
    }

    const sortedFiles = [...files].sort();

    if (options.output) {
      const schemaCode = compiler.processFiles(sortedFiles);
      const outPath = path.resolve(options.output);
      mkdirSync(path.dirname(outPath), { recursive: true });
      const finalOutput = `/**\n * GENERATED BY SAV COMPILER\n * DO NOT EDIT MANUALLY\n */\n${schemaCode}`;
      writeFileSync(outPath, finalOutput);
      console.log(`SAV: Generated ${path.relative(process.cwd(), outPath)}`);
      return;
    }

    let generatedCount = 0;

    for (const file of sortedFiles) {
      const schemaCode = compiler.processFile(file);

      if (!schemaCode.includes("v.object")) {
        continue;
      }

      const fileObject = path.parse(file);
      const outPath = path.join(fileObject.dir, `${fileObject.name}.gen.ts`);
      const finalOutput = `/**\n * GENERATED BY SAV COMPILER\n * DO NOT EDIT MANUALLY\n */\n${schemaCode}`;

      writeFileSync(outPath, finalOutput);
      console.log(`SAV: Generated ${path.relative(process.cwd(), outPath)}`);
      generatedCount += 1;
    }

    console.log(`SAV: Successfully generated ${generatedCount} schema files.`);
  });

program.parse();
