/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

export const PrimitiveShowcaseDTOSchema = v.object({
  amount: v.bigint(),
  token: v.symbol(),
  rawPayload: v.unknown(),
  passthrough: v.any(),
  explicitNull: v.null_(),
  explicitUndefined: v.undefined_(),
  noReturn: v.void_(),
  enabled: v.literal(true),
  disabled: v.literal(false),
  buildNumber: v.literal(2),
});
