/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

export const UserDTOSchema = v.object({
  email: v.string(),
  age: v.coerce(v.number(), (input) => input === "" ? Number.NaN : Number(input)),
  avatar: v.special<File>((input) => input instanceof File),
});

