/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

export const AuditInfoDTOSchema = v.object({
  createdAt: v.transform(v.string(), v => new Date(v), v.date()),
  createdBy: v.string(),
});
