/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

import { EmailChannelDTOSchema } from "./email-channel-dto.schema";
import { SmsChannelDTOSchema } from "./sms-channel-dto.schema";
import { AuditInfoDTOSchema } from "./audit-info-dto.schema";
import { RevisionInfoDTOSchema } from "./revision-info-dto.schema";

export const NotificationRuleDTOSchema = v.object({
  channel: v.union([EmailChannelDTOSchema, SmsChannelDTOSchema]),
  metadata: v.intersect([AuditInfoDTOSchema, RevisionInfoDTOSchema]),
  retries: v.array(v.transform(v.string(), (input) => input === "" ? Number.NaN : Number(input), v.number())),
  deliveryWindow: v.tuple([v.transform(v.string(), v => new Date(v), v.date()), v.transform(v.string(), v => new Date(v), v.date())]),
  mode: v.picklist(["immediate", "digest"]),
});
