/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

export const RevisionInfoDTOSchema = v.object({
  revision: v.transform(v.string(), (input) => input === "" ? Number.NaN : Number(input), v.number()),
});
