/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

export const UserDTOSchema = v.object({
  email: v.string(),
  age: v.transform(v.string(), (input) => input === "" ? Number.NaN : Number(input), v.number()),
  avatar: v.instance(File),
});
