/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

import { CustomerContactDTOSchema } from "./customer-contact-dto.gen";
import { CustomerAddressDTOSchema } from "./customer-address-dto.gen";

export const CustomerInfoDTOSchema = v.object({
  username: v.string(),
  fullName: v.string(),
  firstName: v.string(),
  lastName: v.string(),
  isExistingCustomer: v.transform(v.unknown(), v => v === "on" || v === "true" || v === true, v.boolean()),
  avatar: v.instance(File),
  address: CustomerAddressDTOSchema,
  contact: CustomerContactDTOSchema,
});
