/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

export const CustomerContactDTOSchema = v.object({
  email: v.array(v.string()),
  phoneNumbers: v.array(v.string()),
});
