/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
import * as v from "valibot";

export const CustomerAddressDTOSchema = v.object({
  street: v.string(),
  city: v.string(),
  postalCode: v.string(),
  building: v.optional(v.string()),
});
