/**
 * GENERATED BY SAV COMPILER
 * DO NOT EDIT MANUALLY
 */
export { CustomerInfoDTOSchema } from "./customer-info-dto.gen";
export { CustomerContactDTOSchema } from "./customer-contact-dto.gen";
export { CustomerAddressDTOSchema } from "./customer-address-dto.gen";
